---
- name: Update packages and clean
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true
    cache_valid_time: 3600
    autoremove: "{{ upgrade_packages_autoremove }}"
    clean: "{{ upgrade_packages_clean }}"

- name: Check if reboot is required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Reboot server
  ansible.builtin.reboot:
    post_reboot_delay: 30
  when: reboot_required.stat.exists
