---
- name: Update packages # noqa: package-latest
  ansible.builtin.yum:
    name: "*"
    state: latest

- name: Autoremove packages
  ansible.builtin.yum:
    autoremove: "{{ upgrade_packages_autoremove }}"
